Support Node 8
EnoahNetzach/extract-scss-variables pull request #4
Opened 2017-11-07 23:00 UTC by DanielGibbsNZ

I have a project that is dependant on this module, which prevents me from updating to Node 8.

2017-12-13 09:57 UTC, danielveit approved these changes

2017-12-13 10:30 UTC, Floooorian approved these changes

2017-12-13 15:03 UTC, EnoahNetzach requested changes

2017-12-13 15:03 UTC, EnoahNetzach commented on package.json
> +    "node": "^4 || ^6 || ^7 || ^8"
I'd say at this point to just support `>=4` 

2017-12-13 19:26 UTC, DanielGibbsNZ commented
Updated.

2017-12-15 16:10 UTC, EnoahNetzach approved these changes

2017-12-15 16:11 UTC, merged